version: "3.8"

services:
  postgres:
    container_name: next_postgres
    image: postgres
    restart: always
    networks:
      - app-tier
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U postgres" ]
          interval: 5s
          timeout: 5s
          retries: 5
    ports:
      - 5432:5432
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - app-tier
    depends_on:
      - postgres
    links:
      - postgres
  migration:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migration
    command: npm run db:migrate
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
    links:
      - postgres

networks:
  app-tier:
    driver: bridge