version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=planner
    ports:
      - "5432:5432"
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "dev"]
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  migration:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migration
    command: [ "./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "db:migrate" ]
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres